# -*- coding: utf-8 -*-
"""Copia_de_SimCLR_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUfhAqs5W30ynHXmo3d0sTELOnS-IDQW

# SimCLR
PyTorch implementation of SimCLR: A Simple Framework for Contrastive Learning of Visual Representations by T. Chen et al. With support for the LARS (Layer-wise Adaptive Rate Scaling) optimizer and global batch norm.

[Link to paper](https://arxiv.org/pdf/2002.05709.pdf)

## Setup the repository
"""



"""# Part 1:
## SimCLR pre-training
"""

# whether to use a TPU or not (set in Runtime -> Change Runtime Type)
use_tpu = False

# !pip install torch_xla[tpu] -f https://storage.googleapis.com/libtpu-releases/index.html
# %cd ..

"""#### Install PyTorch/XLA"""

if use_tpu:
  VERSION = "20200220" #@param ["20200220","nightly", "xrt==1.15.0"]
#   !curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
#   !python pytorch-xla-env-setup.py --version $VERSION


import os
import torch
import numpy as np

if use_tpu:
  # imports the torch_xla package for TPU support
  import torch_xla
  import torch_xla.core.xla_model as xm
  dev = xm.xla_device()
  print(dev)

import torchvision
import argparse

from torch.utils.tensorboard import SummaryWriter

apex = False
try:
    from apex import amp
    apex = True
except ImportError:
    print(
        "Install the apex package from https://www.github.com/nvidia/apex to use fp16 for training"
    )

from model import save_model, load_optimizer
from simclr import SimCLR
from simclr.modules import get_resnet, NT_Xent
from simclr.modules.transformations import TransformsSimCLR

"""### Load arguments from `config/config.yaml`"""

from pprint import pprint
import argparse
from utils import yaml_config_hook

parser = argparse.ArgumentParser(description="SimCLR")
config = yaml_config_hook("./config/config.yaml")
for k, v in config.items():
    parser.add_argument(f"--{k}", default=v, type=type(v))

args = parser.parse_args([])
args.device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

### override any configuration parameters here, e.g. to adjust for use on GPUs on the Colab platform:


# distributed training
args.nodes= 1
args.gpus= 1 # I recommend always assigning 1 GPU to 1 node
args.nr= 0 # machine nr. in node (0 -- nodes - 1)
args.dataparallel= 0 # Use DataParallel instead of DistributedDataParallel
args.workers= 8
args.dataset_dir= "./datasets"

# train options
args.seed= 42 # sacred handles automatic seeding when passed in the config
args.batch_size= 128
args.image_size= 32
args.start_epoch= 0
args.epochs= 600
args.dataset= "CIFAR10" # STL10
args.pretrain= True 

# model options
args.resnet= "resnet34"
args.projection_dim= 64 # "[...] to project the representation to a 128-dimensional latent space"

# loss options
args.optimizer= "Adam" # or LARS (experimental)
args.weight_decay= 1.0e-6 # "optimized using LARS [...] and weight decay of 10âˆ’6"
args.temperature= 0.5 # see appendix B.7.= Optimal temperature under different batch sizes

# reload options
args.model_path= "save" # set to the directory containing `checkpoint_##.tar` 
args.epoch_num= 100 # set to checkpoint number
args.reload= False

# logistic regression options
args.logistic_batch_size= 256
args.logistic_epochs= 500



## CUSTOM ARGUMENTS ##

args.dataset= "CIFAR10" 

if args.dataset == 'cifar10' or args.dataset == 'cifar100':
    args.num_classes = 10
    args.image_size = 32
    # args.resnet = "resnet18"

if args.dataset == 'food101N':
    args.num_classes = 101
    args.image_size = 224
    args.resnet = "resnet50"

if args.dataset == 'ANIMAL10N':
    args.num_classes = 10
    args.image_size = 32
    args.resnet = "resnet18"

if args.dataset == 'tiny_imagenet':
    args.num_classes = 200
    args.image_size = 32
    args.resnet = "resnet18"

print(vars(args))



# Commented out IPython magic to ensure Python compatibility.
# %cd ..


# Commented out IPython magic to ensure Python compatibility.
# %cd SimCLR

import logging
import random

import numpy as np
import PIL
import PIL.ImageOps
import PIL.ImageEnhance
import PIL.ImageDraw
from PIL import Image
from torchvision import transforms
#from randaugmentFix import  RandAugmentMC

logger = logging.getLogger(__name__)

PARAMETER_MAX = 10


def AutoContrast(img, **kwarg):
    return PIL.ImageOps.autocontrast(img)


def Brightness(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    return PIL.ImageEnhance.Brightness(img).enhance(v)


def Color(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    return PIL.ImageEnhance.Color(img).enhance(v)


def Contrast(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    return PIL.ImageEnhance.Contrast(img).enhance(v)


def Cutout(img, v, max_v, bias=0):
    if v == 0:
        return img
    v = _float_parameter(v, max_v) + bias
    v = int(v * min(img.size))
    return CutoutAbs(img, v)


def CutoutAbs(img, v, **kwarg):
    w, h = img.size
    x0 = np.random.uniform(0, w)
    y0 = np.random.uniform(0, h)
    x0 = int(max(0, x0 - v / 2.))
    y0 = int(max(0, y0 - v / 2.))
    x1 = int(min(w, x0 + v))
    y1 = int(min(h, y0 + v))
    xy = (x0, y0, x1, y1)
    # gray
    color = (127, 127, 127)
    img = img.copy()
    PIL.ImageDraw.Draw(img).rectangle(xy, color)
    return img


def Equalize(img, **kwarg):
    return PIL.ImageOps.equalize(img)


def Identity(img, **kwarg):
    return img


def Invert(img, **kwarg):
    return PIL.ImageOps.invert(img)


def Posterize(img, v, max_v, bias=0):
    v = _int_parameter(v, max_v) + bias
    return PIL.ImageOps.posterize(img, v)


def Rotate(img, v, max_v, bias=0):
    v = _int_parameter(v, max_v) + bias
    if random.random() < 0.5:
        v = -v
    return img.rotate(v)


def Sharpness(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    return PIL.ImageEnhance.Sharpness(img).enhance(v)


def ShearX(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    if random.random() < 0.5:
        v = -v
    return img.transform(img.size, PIL.Image.AFFINE, (1, v, 0, 0, 1, 0))


def ShearY(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    if random.random() < 0.5:
        v = -v
    return img.transform(img.size, PIL.Image.AFFINE, (1, 0, 0, v, 1, 0))


def Solarize(img, v, max_v, bias=0):
    v = _int_parameter(v, max_v) + bias
    return PIL.ImageOps.solarize(img, 256 - v)


def SolarizeAdd(img, v, max_v, bias=0, threshold=128):
    v = _int_parameter(v, max_v) + bias
    if random.random() < 0.5:
        v = -v
    img_np = np.array(img).astype(int)
    img_np = img_np + v
    img_np = np.clip(img_np, 0, 255)
    img_np = img_np.astype(np.uint8)
    img = Image.fromarray(img_np)
    return PIL.ImageOps.solarize(img, threshold)


def TranslateX(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    if random.random() < 0.5:
        v = -v
    v = int(v * img.size[0])
    return img.transform(img.size, PIL.Image.AFFINE, (1, 0, v, 0, 1, 0))


def TranslateY(img, v, max_v, bias=0):
    v = _float_parameter(v, max_v) + bias
    if random.random() < 0.5:
        v = -v
    v = int(v * img.size[1])
    return img.transform(img.size, PIL.Image.AFFINE, (1, 0, 0, 0, 1, v))


def _float_parameter(v, max_v):
    return float(v) * max_v / PARAMETER_MAX


def _int_parameter(v, max_v):
    return int(v * max_v / PARAMETER_MAX)


def fixmatch_augment_pool():
    # FixMatch paper
    augs = [(AutoContrast, None, None),
            (Brightness, 0.9, 0.05),
            (Color, 0.9, 0.05),
            (Contrast, 0.9, 0.05),
            (Equalize, None, None),
            (Identity, None, None),
            (Posterize, 4, 4),
            (Rotate, 30, 0),
            (Sharpness, 0.9, 0.05),
            (ShearX, 0.3, 0),
            (ShearY, 0.3, 0),
            (Solarize, 256, 0),
            (TranslateX, 0.3, 0),
            (TranslateY, 0.3, 0)]
    return augs


def weak_augment_pool():
    augs = [
            (Contrast, 1.8, 0.1),
            (Cutout, 0.1, 0),
            (Posterize, 4, 4),
            (Rotate, 30, 0),
            (Sharpness, 1.8, 0.1),
            ]
    return augs


def new_augment_pool():
    # Test
    augs = [(AutoContrast, None, None),
            (Brightness, 1.8, 0.1),
            (Color, 1.8, 0.1),
            (Contrast, 1.8, 0.1),
            (Cutout, 0.1, 0),
            (Equalize, None, None),
            (Invert, None, None),
            (Posterize, 4, 4),
            (Rotate, 30, 0),
            (Sharpness, 1.8, 0.1),
            (ShearX, 0.1, 0),
            (ShearY, 0.1, 0),
            (Solarize, 256, 0),
            (SolarizeAdd, 110, 0),
            (TranslateX, 0.05, 0),
            (TranslateY, 0.05, 0)
            ]
    return augs


class RandAugmentMC(object):
    def __init__(self, n, m):
        assert n >= 1
        assert 1 <= m <= 10
        self.n = n
        self.m = m
        self.augment_pool = fixmatch_augment_pool()

    def __call__(self, img):
        ops = random.choices(self.augment_pool, k=self.n)
        for op, max_v, bias in ops:
            v = np.random.randint(1, self.m)
            if random.random() < 0.5:
                img = op(img, v=v, max_v=max_v, bias=bias)
        img = CutoutAbs(img, int(32*0.5))
        return img


class RandAugmentMCLarge(object):
    def __init__(self, n, m):
        assert n >= 1
        assert 1 <= m <= 10
        self.n = n
        self.m = m
        self.augment_pool = new_augment_pool()

    def __call__(self, img):
        ops = random.choices(self.augment_pool, k=self.n)
        for op, max_v, bias in ops:
            v = np.random.randint(1, self.m)
            if random.random() < 0.5:
                img = op(img, v=v, max_v=max_v, bias=bias)
        img = CutoutAbs(img, int(224*0.1))
        return img


class RandAugmentwogeo(object):
    def __init__(self, n, m):
        assert n >= 1
        assert 1 <= m <= 10
        self.n = n
        self.m = m
        self.augment_pool = new_augment_pool()

    def __call__(self, img):
        ops = random.choices(self.augment_pool, k=self.n)
        for op, max_v, bias in ops:
            v = np.random.randint(1, self.m)
            if random.random() < 0.5:
                img = op(img, v=v, max_v=max_v, bias=bias)
        size = img.size[0]
        img = CutoutAbs(img, int(size * 0.15))
        return img


class TransformFixMatch_CIFAR10(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect')
            ]
        )
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=5)])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)


class Transform2Weak_CIFAR10(object):
    def __init__(self, mean, std):
        self.weak1 = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            transforms.RandomGrayscale(p=0.3),
            ]
        )
        self.weak2 = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            transforms.RandomApply([transforms.ColorJitter(0.4, 0.4, 0.4, 0.1)], p=0.3)
            ]
        )
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak1 = self.weak1(x)
        weak2 = self.weak2(x)
        return self.normalize(weak1), self.normalize(weak2)


class Transform2Weak_CIFAR100(object):
    def __init__(self, mean, std):
        self.weak1 = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            transforms.RandomGrayscale(p=0.3),
            ]
        )
        self.weak2 = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            transforms.RandomApply([transforms.ColorJitter(0.4, 0.4, 0.4, 0.1)], p=0.3)
            ]
        )
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak1 = self.weak1(x)
        weak2 = self.weak2(x)
        return self.normalize(weak1), self.normalize(weak2)


class TransformFixMatch(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect')
            ]
        )
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=10)])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)


class TransformFixMatch_CIFAR100(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect')
            ]
        )
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=10)])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)

class TransformFixMatch_CIFAR100N(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect')
            ]
        )
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=10)])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)

class TransformFixMatch(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect')])
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,padding=int(32*0.125),padding_mode='reflect'),
            RandAugmentMC(n=2, m=10)])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)



class Transform_2strong_CIFAR100(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect')
            ]
        )
        self.strong1 = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=5)])
        self.strong2 = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=5)])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong1 = self.strong1(x)
        strong2 = self.strong2(x)
        return self.normalize(weak), self.normalize(strong1), self.normalize(strong2)


class TransformFixMatchMedium(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=64,
                                  padding=int(64*0.125),
                                  padding_mode='reflect')])
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=64,
                                  padding=int(64*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=10)])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)


class TransformFixMatchLarge(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            transforms.Resize(256),
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=224,
                                  padding=int(224*0.125),
                                  padding_mode='reflect')
            ])
        self.strong = transforms.Compose([
            transforms.Resize(256),
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=224,
                                  padding=int(224*0.125),
                                  padding_mode='reflect'),
            RandAugmentwogeo(n=2, m=10)]) #TODO 2,10
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)


class TransformFixMatchMax(object):
    def __init__(self, mean, std):
        self.weak = transforms.Compose([
            # transforms.Resize(size=330),
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=256,
                                  padding=int(256*0.125),
                                  padding_mode='reflect')
            ])
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomResizedCrop(256, scale=(0.4,1.)),
            RandAugmentwogeo(n=5, m=10)
            ])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        weak = self.weak(x)
        strong = self.strong(x)
        return self.normalize(weak), self.normalize(strong)


class TransformsSimCLR(object):
    """
    A stochastic data augmentation module that transforms any given data example randomly
    resulting in two correlated views of the same example,
    denoted x ̃i and x ̃j, which we consider as a positive pair.
    """

    def __init__(self, size):
        s = 1
        color_jitter = transforms.ColorJitter(
            0.8 * s, 0.8 * s, 0.8 * s, 0.2 * s
        )
        self.train_transform = transforms.Compose(
            [
                transforms.RandomResizedCrop(size=size),
                transforms.RandomHorizontalFlip(),  # with 0.5 probability
                transforms.RandomApply([color_jitter], p=0.8),
                transforms.RandomGrayscale(p=0.2),
                transforms.ToTensor(),
            ]
        )

        self.test_transform = transforms.Compose([
                transforms.Resize(size=size),
                transforms.ToTensor(),])

    def __call__(self, x):
        return self.train_transform(x), self.train_transform(x)

# !pip install ipdb





import os
import os.path
import hashlib
import pickle
import numpy as np
from numpy.testing import assert_array_almost_equal


def get_gt_labels(dataset, root):
    if dataset == 'cifar10':
        train_list = [
            ['data_batch_1', 'c99cafc152244af753f735de768cd75f'],
            ['data_batch_2', 'd4bba439e000b95fd0a9bffe97cbabec'],
            ['data_batch_3', '54ebc095f3ab1f0389bbae665268c751'],
            ['data_batch_4', '634d18415352ddfa80567beed471001a'],
            ['data_batch_5', '482c414d41f54cd18b22e5b47cb7c3cb'],
        ]
        base_folder = 'cifar-10-batches-py'
    elif dataset == 'cifar100':
        train_list = [
            ['train', '16019d7e3df5f24257cddd939b257f8d'],
        ]
        base_folder = 'cifar-100-python'
    targets = []
    for file_name, checksum in train_list:
        file_path = os.path.join(root, base_folder, file_name)
        with open(file_path, 'rb') as f:
            entry = pickle.load(f, encoding='latin1')
            if 'labels' in entry:
                targets.extend(entry['labels'])
            else:
                targets.extend(entry['fine_labels'])
    return targets


def check_integrity(fpath, md5):
    if not os.path.isfile(fpath):
        return False
    md5o = hashlib.md5()
    with open(fpath, 'rb') as f:
        # read in 1MB chunks
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            md5o.update(chunk)
    md5c = md5o.hexdigest()
    if md5c != md5:
        return False
    return True


def list_dir(root, prefix=False):
    """List all directories at a given root

    Args:
        root (str): Path to directory whose folders need to be listed
        prefix (bool, optional): If true, prepends the path to each result, otherwise
            only returns the name of the directories found
    """
    root = os.path.expanduser(root)
    directories = list(
        filter(lambda p: os.path.isdir(os.path.join(root, p)),
               os.listdir(root)))

    if prefix is True:
        directories = [os.path.join(root, d) for d in directories]

    return directories


def list_files(root, suffix, prefix=False):
    """List all files ending with a suffix at a given root

    Args:
        root (str): Path to directory whose folders need to be listed
        suffix (str or tuple): Suffix of the files to match, e.g. '.png' or ('.jpg', '.png').
            It uses the Python "str.endswith" method and is passed directly
        prefix (bool, optional): If true, prepends the path to each result, otherwise
            only returns the name of the files found
    """
    root = os.path.expanduser(root)
    files = list(
        filter(
            lambda p: os.path.isfile(os.path.join(root, p)) and p.endswith(
                suffix), os.listdir(root)))

    if prefix is True:
        files = [os.path.join(root, d) for d in files]

    return files


def build_for_cifar100(size, noise):
    """ The noise matrix flips to the "next" class with probability 'noise'.
    """

    assert (noise >= 0.) and (noise <= 1.)

    P = (1. - noise) * np.eye(size)
    for i in np.arange(size - 1):
        P[i, i + 1] = noise

    # adjust last row
    P[size - 1, 0] = noise

    assert_array_almost_equal(P.sum(axis=1), 1, 1)
    return P


# basic function
def multiclass_noisify(y, P, seed=0):
    """ Flip classes according to transition probability matrix T.
    It expects a number between 0 and the number of classes - 1.
    """
    print(np.max(y), P.shape[0])
    assert P.shape[0] == P.shape[1]
    assert np.max(y) < P.shape[0]

    # row stochastic matrix
    assert_array_almost_equal(P.sum(axis=1), np.ones(P.shape[1]))
    assert (P >= 0.0).all()

    m = y.shape[0]
    print(m)
    new_y = y.copy()
    flipper = np.random.RandomState(seed)

    for idx in np.arange(m):
        i = y[idx]
        # draw a vector with only an 1
        flipped = flipper.multinomial(1, P[i, :][0], 1)[0]
        new_y[idx] = np.where(flipped == 1)[0]

    return new_y


# noisify_pairflip call the function "multiclass_noisify"
def noisify_pairflip(y_train, noise, seed=None, nb_classes=10):
    """mistakes:
        flip in the pair
    """
    P = np.eye(nb_classes)
    n = noise

    if n > 0.0:
        # 0 -> 1
        P[0, 0], P[0, 1] = 1. - n, n
        for i in range(1, nb_classes - 1):
            P[i, i], P[i, i + 1] = 1. - n, n
        P[nb_classes - 1, nb_classes - 1], P[nb_classes - 1, 0] = 1. - n, n

        y_train_noisy = multiclass_noisify(y_train,
                                           P=P,
                                           seed=seed)
        actual_noise = (y_train_noisy != y_train).mean()
        assert actual_noise > 0.0
        print('Actual noise %.2f' % actual_noise)
        y_train = y_train_noisy
    print(P)

    return y_train, actual_noise


def noisify_multiclass_symmetric(y_train,
                                 noise,
                                 seed=None,
                                 nb_classes=10):
    """mistakes:
        flip in the symmetric way
    """
    P = np.ones((nb_classes, nb_classes))
    n = noise
    P = (n / (nb_classes - 1)) * P

    if n > 0.0:
        # 0 -> 1
        P[0, 0] = 1. - n
        for i in range(1, nb_classes - 1):
            P[i, i] = 1. - n
        P[nb_classes - 1, nb_classes - 1] = 1. - n

        y_train_noisy = multiclass_noisify(y_train,
                                           P=P,
                                           seed=seed)
        actual_noise = (y_train_noisy != y_train).mean()
        assert actual_noise > 0.0
        print('Actual noise %.2f' % actual_noise)
        y_train = y_train_noisy
    print(P)

    return y_train, actual_noise


def noisify_mnist_asymmetric(y_train, noise, seed=None):
    """mistakes:
        1 <- 7
        2 -> 7
        3 -> 8
        5 <-> 6
    """
    nb_classes = 10
    P = np.eye(nb_classes)
    n = noise

    if n > 0.0:
        # 1 <- 7
        P[7, 7], P[7, 1] = 1. - n, n

        # 2 -> 7
        P[2, 2], P[2, 7] = 1. - n, n

        # 5 <-> 6
        P[5, 5], P[5, 6] = 1. - n, n
        P[6, 6], P[6, 5] = 1. - n, n

        # 3 -> 8
        P[3, 3], P[3, 8] = 1. - n, n

        y_train_noisy = multiclass_noisify(y_train,
                                           P=P,
                                           seed=seed)
        actual_noise = (y_train_noisy != y_train).mean()
        assert actual_noise > 0.0
        print('Actual noise %.2f' % actual_noise)
        y_train = y_train_noisy

    print(P)

    return y_train, P


def noisify_cifar10_asymmetric(y_train, noise, seed=None):
    """mistakes:
        automobile <- truck
        bird -> airplane
        cat <-> dog
        deer -> horse
    """
    nb_classes = 10
    P = np.eye(nb_classes)
    n = noise

    if n > 0.0:
        # automobile <- truck
        P[9, 9], P[9, 1] = 1. - n, n

        # bird -> airplane
        P[2, 2], P[2, 0] = 1. - n, n

        # cat <-> dog
        P[3, 3], P[3, 5] = 1. - n, n
        P[5, 5], P[5, 3] = 1. - n, n

        # automobile -> truck
        P[4, 4], P[4, 7] = 1. - n, n

        y_train_noisy = multiclass_noisify(y_train,
                                           P=P,
                                           seed=seed)
        actual_noise = (y_train_noisy != y_train).mean()
        assert actual_noise > 0.0
        print('Actual noise %.2f' % actual_noise)
        y_train = y_train_noisy

    return y_train, P


def noisify_cifar100_asymmetric(y_train, noise, seed=None):
    """mistakes are inside the same superclass of 10 classes, e.g. 'fish'
    """
    nb_classes = 100
    P = np.eye(nb_classes)
    n = noise
    nb_superclasses = 20
    nb_subclasses = 5

    if n > 0.0:
        for i in np.arange(nb_superclasses):
            init, end = i * nb_subclasses, (i + 1) * nb_subclasses
            P[init:end, init:end] = build_for_cifar100(nb_subclasses, n)

        y_train_noisy = multiclass_noisify(y_train,
                                           P=P,
                                           seed=seed)
        actual_noise = (y_train_noisy != y_train).mean()
        assert actual_noise > 0.0
        print('Actual noise %.2f' % actual_noise)
        y_train = y_train_noisy

    return y_train, P


def noisify(dataset='mnist',
            nb_classes=10,
            train_labels=None,
            noise_type=None,
            noise_rate=0,
            random_state=0,
            seed=0):
    if noise_type == 'pairflip':
        train_noisy_labels, actual_noise_rate = noisify_pairflip(
            train_labels,
            noise_rate,
            seed=seed,
            nb_classes=nb_classes)
    if noise_type == 'sym':
        train_noisy_labels, actual_noise_rate = noisify_multiclass_symmetric(
            train_labels,
            noise_rate,
            seed=seed,
            nb_classes=nb_classes)
    if noise_type == 'asym':
        if dataset == 'mnist':
            train_noisy_labels, actual_noise_rate = noisify_mnist_asymmetric(
                train_labels, noise_rate, seed=seed)
        elif dataset == 'cifar10':
            train_noisy_labels, actual_noise_rate = noisify_cifar10_asymmetric(
                train_labels, noise_rate, seed=seed)
        elif dataset == 'cifar100':
            train_noisy_labels, actual_noise_rate = noisify_cifar100_asymmetric(
                train_labels, noise_rate, seed=seed)
    return train_noisy_labels, actual_noise_rate



from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import random
import numpy as np
from PIL import Image
import os


class animal10N_dataset(Dataset):

    def __init__(self, root_dir, mode):

        self.root_dir = root_dir
        self.mode = mode
        self.transform_test = transforms.Compose([
            # transforms.Resize(64),
            # transforms.CenterCrop(64),
            transforms.ToTensor(),
            transforms.Normalize((0.6959, 0.6537, 0.6371),
                                 (0.3113, 0.3192, 0.3214)),
        ])
        self.transform_train = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(64),
            transforms.ToTensor(),
            transforms.Normalize((0.6959, 0.6537, 0.6371),
                                 (0.3113, 0.3192, 0.3214)),
        ])
        self.transform_fixmatch = TransformFixMatchMedium(
            (0.6959, 0.6537, 0.6371), (0.3113, 0.3192, 0.3214))

        self.transform_simclr=TransformsSimCLR(64)

        self.train_dir = root_dir + '/training/'
        self.test_dir = root_dir + '/testing/'
    
        train_imgs = os.listdir(self.train_dir)
        test_imgs = os.listdir(self.test_dir)


        self.train_imgs = []
        self.test_imgs = []

        for img in train_imgs:
            self.train_imgs.append([img, int(img[0])])
        for img in test_imgs:
            self.test_imgs.append([img, int(img[0])])
        print(len(train_imgs))

    def __getitem__(self, index):

        if self.mode == 'train':
            img_id, target = self.train_imgs[index]
            img_path = self.train_dir + img_id
            image = Image.open(img_path).convert('RGB')
            img = self.transform_fixmatch(image)
            return img, target


        elif self.mode == 'test':
            ind = index
            img_id, target = self.test_imgs[index]
            img_path = self.test_dir + img_id
            image = Image.open(img_path).convert('RGB')
            img = self.transform_test(image)
            return img, target

    def __len__(self):
        if self.mode == 'test':
            return len(self.test_imgs)
        elif self.mode == 'train' :
            return len(self.train_imgs)


class animal10N_dataloader():

    def __init__(self, root_dir, batch_size, num_workers, num_batches=1000):
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.root_dir = root_dir
        self.num_batches = num_batches

    def run(self, mode='full_train_noisy_test'):
        print('=============================================================> Loading data...')
        print('Mode:', mode)


        train_dataset = animal10N_dataset(root_dir=self.root_dir, mode=mode)
        train_loader = DataLoader(dataset=train_dataset,
                                  batch_size=self.batch_size,
                                  shuffle=True,
                                  drop_last=True,
                                  num_workers=self.num_workers,
                                  pin_memory=True)

        test_dataset = animal10N_dataset(root_dir=self.root_dir, mode='test')
        test_loader = DataLoader(dataset=test_dataset,
                                 batch_size=self.batch_size,
                                 shuffle=False,
                                 drop_last=True,
                                 num_workers=self.num_workers,
                                 pin_memory=True)

        return train_loader, test_loader






import torchvision
from torch.utils.data import DataLoader
import torchvision.transforms as transforms
import numpy as np
from PIL import Image
import torch

from PIL import Image
import os
import os.path
from typing import Any, Callable, cast, Dict, List, Optional, Tuple
# from .utils import *

IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif',
                  '.tiff', '.webp')
device = torch.device('cuda') if torch.cuda.is_available() else torch.device(
    'cpu')


class NoiseDataset(torchvision.datasets.VisionDataset):

    def __init__(
        self,
        noise_type: str = 'none',
        asym_trans: dict = None,
        percent: float = 0.0,
    ) -> None:

        assert percent <= 1.0 and percent >= 0.0
        assert noise_type in ['sym', 'asym', 'ins', 'none']

        self.percent = percent
        self.noise_type = noise_type
        self.asym_trans = asym_trans

        # dataset info
        self.min_target = min(self.targets)
        self.max_target = max(self.targets)
        self.num_classes = len(np.unique(self.targets))
        assert self.num_classes == self.max_target - self.min_target + 1
        self.num_samples = len(self.targets)

        self.transform_simclr=TransformsSimCLR(64)

        if self.noise_type == 'sym':
            self.symmetric_noise()
        elif self.noise_type == 'asym':
            self.asymmetric_noise()
        elif self.noise_type == 'ins':
            self.instance_noise(tau=self.percent)

    def symmetric_noise(self):
        type = 1

        if type == 1:  # The noisy labels may include clean labels
            indices = np.random.permutation(len(self.data))
            for i, idx in enumerate(indices):
                if i < self.percent * len(self.data):
                    self.targets[idx] = np.random.randint(
                        low=self.min_target,
                        high=self.max_target + 1,
                        dtype=np.int32)
        else:
            random_state = 0
            dataset = 'tiny_imagenet'
            train_noisy_labels, actual_noise_rate = noisify(
                dataset=dataset,
                train_labels=np.array(self.targets).reshape(
                    [len(self.targets), 1]),
                noise_type=self.noise_type,
                noise_rate=self.percent,
                random_state=random_state,
                nb_classes=self.num_classes)
            self.targets = [int(label) for label in train_noisy_labels]
            print("Actual noise rate is %.4f" % actual_noise_rate)

    def asymmetric_noise(self):
        type = 2
        random_state = 0
        dataset = 'tiny_imagenet'
        self.noise_type = 'pairflip'
        train_noisy_labels, actual_noise_rate = noisify(
            dataset=dataset,
            train_labels=np.array(self.targets).reshape([len(self.targets),
                                                         1]),
            noise_type=self.noise_type,
            noise_rate=self.percent,
            random_state=random_state,
            nb_classes=self.num_classes)
        self.targets = [int(label) for label in train_noisy_labels]
        print("Actual noise rate is %.4f" % actual_noise_rate)

    def instance_noise(
        self,
        tau: float = 0.2,
        std: float = 0.1,
        feature_size: int = 3 * 32 * 32,
    ):
        '''
        Thanks the code from https://github.com/SML-Group/Label-Noise-Learning wrote by SML-Group.
        LabNoise referred much about the generation of instance-dependent label noise from this repo.
        '''
        from scipy import stats
        from math import inf
        import torch.nn.functional as F

        # np.random.seed(int(seed))
        # torch.manual_seed(int(seed))
        # torch.cuda.manual_seed(int(seed))

        # common-used parameters
        num_samples = self.num_samples
        num_classes = self.num_classes

        P = []
        # sample instance flip rates q from the truncated normal distribution N(\tau, {0.1}^2, [0, 1])
        flip_distribution = stats.truncnorm((0 - tau) / std, (1 - tau) / std,
                                            loc=tau,
                                            scale=std)
        '''
        The standard form of this distribution is a standard normal truncated to the range [a, b]
        notice that a and b are defined over the domain of the standard normal.
        To convert clip values for a specific mean and standard deviation, use:

        a, b = (myclip_a - my_mean) / my_std, (myclip_b - my_mean) / my_std
        truncnorm takes  and  as shape parameters.

        so the above `flip_distribution' give a truncated standard normal distribution with mean = `tau`,
        range = [0, 1], std = `std`
        '''
        # import ipdb; ipdb.set_trace()
        # how many random variates you need to get
        q = flip_distribution.rvs(num_samples)
        # sample W \in \mathcal{R}^{S \times K} from the standard normal distribution N(0, 1^2)
        W = torch.tensor(
            np.random.randn(num_classes, feature_size,
                            num_classes)).float().to(
                                device)  #K*dim*K, dim=3072
        for i in range(num_samples):
            x, y = self.transform(Image.fromarray(self.data[i])), torch.tensor(
                self.targets[i])
            x = x.to(device)
            # step (4). generate instance-dependent flip rates
            # 1 x feature_size  *  feature_size x 10 = 1 x 10, p is a 1 x 10 vector
            p = x.reshape(1, -1).mm(W[y]).squeeze(0)  #classes
            # step (5). control the diagonal entry of the instance-dependent transition matrix
            # As exp^{-inf} = 0, p_{y} will be 0 after softmax function.
            p[y] = -inf
            # step (6). make the sum of the off-diagonal entries of the y_i-th row to be q_i
            p = q[i] * F.softmax(p, dim=0)
            p[y] += 1 - q[i]
            P.append(p)
        P = torch.stack(P, 0).cpu().numpy()
        l = [i for i in range(self.min_target, self.max_target + 1)]
        new_label = [np.random.choice(l, p=P[i]) for i in range(num_samples)]

        print('noise rate = ', (new_label != np.array(self.targets)).mean())
        self.targets = new_label


def has_file_allowed_extension(filename: str, extensions: Tuple[str,
                                                                ...]) -> bool:
    """Checks if a file is an allowed extension.
    Args:
        filename (string): path to a file
        extensions (tuple of strings): extensions to consider (lowercase)
    Returns:
        bool: True if the filename ends with one of given extensions
    """
    return filename.lower().endswith(extensions)


def is_image_file(filename: str) -> bool:
    """Checks if a file is an allowed image extension.
    Args:
        filename (string): path to a file
    Returns:
        bool: True if the filename ends with a known image extension
    """
    return has_file_allowed_extension(filename, IMG_EXTENSIONS)


def find_classes(directory: str) -> Tuple[List[str], Dict[str, int]]:
    """Finds the class folders in a dataset.
    See :class:`DatasetFolder` for details.
    """
    classes = sorted(entry.name for entry in os.scandir(directory)
                     if entry.is_dir())
    if not classes:
        raise FileNotFoundError(
            f"Couldn't find any class folder in {directory}.")

    class_to_idx = {cls_name: i for i, cls_name in enumerate(classes)}
    return classes, class_to_idx


def make_dataset(
    directory: str,
    class_to_idx: Optional[Dict[str, int]] = None,
    extensions: Optional[Tuple[str, ...]] = None,
    is_valid_file: Optional[Callable[[str], bool]] = None,
) -> List[Tuple[str, int]]:
    """Generates a list of samples of a form (path_to_sample, class).
    See :class:`DatasetFolder` for details.
    Note: The class_to_idx parameter is here optional and will use the logic of the ``find_classes`` function
    by default.
    """
    directory = os.path.expanduser(directory)
    clsa, class_to_idx = find_classes(directory)
    # print(clsa,class_to_idx)
    if class_to_idx is None:
        _, class_to_idx = find_classes(directory)
    elif not class_to_idx:
        raise ValueError(
            "'class_to_index' must have at least one entry to collect any samples."
        )

    both_none = extensions is None and is_valid_file is None
    both_something = extensions is not None and is_valid_file is not None
    if both_none or both_something:
        raise ValueError(
            "Both extensions and is_valid_file cannot be None or not None at the same time"
        )

    if extensions is not None:

        def is_valid_file(x: str) -> bool:
            return has_file_allowed_extension(
                x, cast(Tuple[str, ...], extensions))

    is_valid_file = cast(Callable[[str], bool], is_valid_file)

    instances = []
    available_classes = set()
    for target_class in sorted(class_to_idx.keys()):
        class_index = class_to_idx[target_class]
        target_dir = os.path.join(directory, target_class)
        if not os.path.isdir(target_dir):
            continue
        for root, _, fnames in sorted(os.walk(target_dir, followlinks=True)):
            for fname in sorted(fnames):
                if is_valid_file(fname):
                    path = os.path.join(root, fname)
                    item = path, class_index
                    instances.append(item)

                    if target_class not in available_classes:
                        available_classes.add(target_class)

    empty_classes = set(class_to_idx.keys()) - available_classes
    if empty_classes:
        msg = f"Found no valid file for the classes {', '.join(sorted(empty_classes))}. "
        if extensions is not None:
            msg += f"Supported extensions are: {', '.join(extensions)}"
        raise FileNotFoundError(msg)

    return instances, class_to_idx


class tiny_imagenet_dataloader():

    def __init__(self, root_dir, batch_size, num_workers, noise_type, percent):
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.root_dir = root_dir
        self.noise_type = noise_type
        self.percent = percent

    def run(self, mode='full_train_noisy_test'):
        if mode == 'train':
            train_dataset = tiny_imagenet_dataset(root_dir = self.root_dir, noise_mode=self.noise_type, \
                                                  ratio=self.percent, mode=mode)
            train_loader = DataLoader(dataset=train_dataset,
                                      batch_size=self.batch_size,
                                      shuffle=True,
                                      drop_last=True,
                                      num_workers=self.num_workers,
                                      pin_memory=True)
            return train_loader

        elif mode == 'test':
            test_dataset = tiny_imagenet_dataset(root_dir = self.root_dir, noise_mode=self.noise_type, \
                                                  ratio=self.percent, mode='val')
            test_loader = DataLoader(dataset=test_dataset,
                                     batch_size=self.batch_size,
                                     shuffle=False,
                                     drop_last=True,
                                     num_workers=self.num_workers,
                                     pin_memory=True)
            return test_loader


class tiny_imagenet_dataset(NoiseDataset):

    def __init__(self, root_dir, ratio, noise_mode, mode='train'):
        self.transform_train_weak = transforms.Compose([
            transforms.RandomResizedCrop(32),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
        ])
        self.transform_train_strong = transforms.Compose([
            transforms.RandomResizedCrop(32),
            transforms.RandomHorizontalFlip(),
            transforms.RandomApply(
                [transforms.ColorJitter(0.4, 0.4, 0.4, 0.1)], p=0.8),
            transforms.RandomGrayscale(p=0.5),
            transforms.ToTensor(),
            transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
        ])
        # import ipdb; ipdb.set_trace()

        self.transform_train = TransformFixMatchMedium((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))

        self.transform_test = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
        ])

        self.root = root_dir
        self.ratio = ratio
        self.noise_mode = noise_mode
        self.mode = mode
        ### Get the instances and check if it is right
        if 'train' in mode:
            data_folder = '%s/train/' % self.root
            instances, dict_classes = make_dataset(data_folder,
                                                   extensions=IMG_EXTENSIONS)
        elif mode == 'val':
            ## Validation Files
            data_folder = '%s/val/' % self.root
            _, dict_classes = find_classes(data_folder.replace('val', 'train'))
            instances = make_dataset(data_folder, extensions=IMG_EXTENSIONS)
            val_text = '%s/val/val_annotations.txt' % self.root
            val_img_files = '%s/val/images' % self.root
        elif mode == 'test':
            data_folder = '%s/test/' % self.root
            test_instances = make_dataset(data_folder,
                                          extensions=IMG_EXTENSIONS)

        self.data = []
        self.targets = []

        if 'train' in mode:
            for kk in range(len(instances)):
                path_ind = list(instances[kk])[0]
                self.targets.append(int(list(instances[kk])[1]))
                self.data.append(path_ind)
            NoiseDataset.__init__(self,
                                  noise_type=self.noise_mode,
                                  asym_trans=None,
                                  percent=self.ratio)

        elif mode == 'val':
            with open(val_text, 'r') as f:
                lines = f.read().splitlines()
                for l in lines:
                    entry = l.split()
                    img_path = '%s/' % val_img_files + entry[0]
                    self.targets.append(int(dict_classes[entry[1]]))
                    self.data.append(img_path)

    def __getitem__(self, index):
        img_path, target = self.data[index], self.targets[index]
        # print(img_path)
        image = Image.open(img_path).convert('RGB')


        if self.mode == 'train':
            img =  self.transform_simclr(image)
            return img
            return img, target, index
        elif self.mode == 'val':
            img = self.transform_test(image)
            return img, target

    def __len__(self):
        return len(self.data)


class food101N_dataset(Dataset):

    def __init__(self, root_dir, mode):

        self.root_dir = root_dir
        self.mode = mode

        self.transform_test = transforms.Compose([
            transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize((0.6959, 0.6537, 0.6371),
                                 (0.3113, 0.3192, 0.3214)),
        ])

        self.transform_train = transforms.Compose([
            transforms.Resize(256),
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(224),
            transforms.ToTensor(),
            transforms.Normalize((0.6959, 0.6537, 0.6371),
                                 (0.3113, 0.3192, 0.3214)),
        ])
        self.transform_fixmatch = TransformFixMatchLarge(
            (0.6959, 0.6537, 0.6371), (0.3113, 0.3192, 0.3214))
        
        self.transform_simclr = TransformsSimCLR(224) #Try 256?

        self.imgs_root = root_dir + '/images/'
        train_file = root_dir + '/meta/train.txt'
        test_file = root_dir + '/meta/test.txt'
        imgs_dirs = os.listdir(self.imgs_root)
        imgs_dirs.sort()
        class2idx = {}
        self.train_imgs = []
        self.test_imgs = []

        for idx, food in enumerate(imgs_dirs):
            class2idx[food] = idx

        with open(train_file) as f:
            lines = f.readlines()
            for line in lines:
                train_img = line.strip()
                target = class2idx[train_img.split('/')[0]]
                self.train_imgs.append([train_img, target])
        with open(test_file) as f:
            lines = f.readlines()
            for line in lines:
                test_img = line.strip()
                target = class2idx[test_img.split('/')[0]]
                self.test_imgs.append([test_img, target])

    def __getitem__(self, index):
        if self.mode == 'train':
            img_id, target = self.train_imgs[index]
            img_path = self.imgs_root + img_id + '.jpg'
            image = Image.open(img_path).convert('RGB')
            img =  self.transform_simclr(image)
            return img

        elif self.mode == 'test':
            ind = index
            img_id, target = self.test_imgs[index]
            img_path = self.imgs_root + img_id + '.jpg'
            image = Image.open(img_path).convert('RGB')
            img = self.transform_test(image)
            return img, target

    def __len__(self):
        if self.mode == 'test':
            return len(self.test_imgs)
        elif self.mode == 'train':
            return len(self.train_imgs)


class food101N_dataloader():

    def __init__(self, root_dir, batch_size, num_workers, num_batches=1000):
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.root_dir = root_dir
        self.num_batches = num_batches

    def run(self, mode='train'):
        train_dataset = food101N_dataset(root_dir=self.root_dir, mode=mode)
        train_loader = DataLoader(dataset=train_dataset,
                                  batch_size=self.batch_size,
                                  shuffle=True,drop_last=True,
                                  num_workers=self.num_workers,
                                  pin_memory=True)

        test_dataset = food101N_dataset(root_dir=self.root_dir, mode='test')
        test_loader = DataLoader(dataset=test_dataset,
                                 batch_size=self.batch_size,
                                 shuffle=False,
                                 num_workers=self.num_workers,
                                 pin_memory=True)

        return train_loader, test_loader
    

class CIFAR10(torchvision.datasets.VisionDataset):
    """`CIFAR10 <https://www.cs.toronto.edu/~kriz/cifar.html>`_ Dataset.
    Args:
        root (string): Root directory of dataset where directory
            ``cifar-10-batches-py`` exists or will be saved to if download is set to True.
        train (bool, optional): If True, creates dataset from training set, otherwise
            creates from test set.
        transform (callable, optional): A function/transform that takes in an PIL image
            and returns a transformed version. E.g, ``transforms.RandomCrop``
        target_transform (callable, optional): A function/transform that takes in the
            target and transforms it.
        download (bool, optional): If true, downloads the dataset from the internet and
            puts it in root directory. If dataset is already downloaded, it is not
            downloaded again.
    """
    base_folder = 'cifar-10-batches-py'
    url = "https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz"
    filename = "cifar-10-python.tar.gz"
    tgz_md5 = 'c58f30108f718f92721af3b95e74349a'
    train_list = [
        ['data_batch_1', 'c99cafc152244af753f735de768cd75f'],
        ['data_batch_2', 'd4bba439e000b95fd0a9bffe97cbabec'],
        ['data_batch_3', '54ebc095f3ab1f0389bbae665268c751'],
        ['data_batch_4', '634d18415352ddfa80567beed471001a'],
        ['data_batch_5', '482c414d41f54cd18b22e5b47cb7c3cb'],
    ]

    test_list = [
        ['test_batch', '40351d587109b95175f43aff81a1287e'],
    ]
    meta = {
        'filename': 'batches.meta',
        'key': 'label_names',
        'md5': '5ff9c542aee3614f3951f8cda6e48888',
    }

    def __init__(
            self,
            root: str,
            train: bool = True,
            transform: Optional[Callable] = None,
            target_transform: Optional[Callable] = None,
            download: bool = False,
    ) -> None:
        # import ipdb; ipdb.set_trace()
        self.train = train  # training set or test set
        # self.root = root
        if download:
            self.download()

        if not self._check_integrity():
            raise RuntimeError('Dataset not found or corrupted.' +
                               ' You can use download=True to download it')

        if self.train:
            downloaded_list = self.train_list
        else:
            downloaded_list = self.test_list

        self.data: Any = []
        self.targets = []

        # now load the picked numpy arrays
        for file_name, checksum in downloaded_list:
            file_path = os.path.join(self.root, self.base_folder, file_name)
            with open(file_path, 'rb') as f:
                entry = pickle.load(f, encoding='latin1')
                self.data.append(entry['data'])
                if 'labels' in entry:
                    self.targets.extend(entry['labels'])
                else:
                    self.targets.extend(entry['fine_labels'])

        self.data = np.vstack(self.data).reshape((-1, 3, 32, 32))
        self.data = self.data.transpose((0, 2, 3, 1))  # convert to HWC

        self._load_meta()

    def _load_meta(self) -> None:
        path = os.path.join(self.root, self.base_folder, self.meta['filename'])
        if not check_integrity(path, self.meta['md5']):
            raise RuntimeError('Dataset metadata file not found or corrupted.' +
                               ' You can use download=True to download it')
        with open(path, 'rb') as infile:
            data = pickle.load(infile, encoding='latin1')
            self.classes = data[self.meta['key']]
        self.class_to_idx = {_class: i for i, _class in enumerate(self.classes)}

    def __getitem__(self, index: int) -> Tuple[Any, Any]:
        """
        Args:
            index (int): Index
        Returns:
            tuple: (image, target) where target is index of the target class.
        """
        img, target = self.data[index], self.targets[index]

        # doing this so that it is consistent with all other datasets
        # to return a PIL Image
        img = Image.fromarray(img)

        if self.transform is not None:
            img = self.transform(img)

        if self.target_transform is not None:
            target = self.target_transform(target)

        return img, target

    def __len__(self) -> int:
        return len(self.data)

    def _check_integrity(self) -> bool:
        for fentry in (self.train_list + self.test_list):
            filename, md5 = fentry[0], fentry[1]
            fpath = os.path.join(self.root, self.base_folder, filename)
            if not check_integrity(fpath, md5):
                return False
        return True

    def download(self) -> None:
        if self._check_integrity():
            print('Files already downloaded and verified')
            return
        download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)

    def extra_repr(self) -> str:
        return "Split: {}".format("Train" if self.train is True else "Test")

device = torch.device('cuda') if torch.cuda.is_available() else torch.device(
    'cpu')


class NoiseDataset(torchvision.datasets.VisionDataset):

    def __init__(
        self,
        noise_type: str = 'none',
        asym_trans: dict = None,
        percent: float = 0.0,
    ) -> None:

        assert percent <= 1.0 and percent >= 0.0
        assert noise_type in ['sym', 'asym', 'ins', 'none']

        self.percent = percent
        self.noise_type = noise_type
        self.asym_trans = asym_trans
        self.target_copy = self.targets.copy()

        # dataset info
        self.min_target = min(self.targets)
        self.max_target = max(self.targets)
        self.num_classes = len(np.unique(self.targets))
        assert self.num_classes == self.max_target - self.min_target + 1
        self.num_samples = len(self.targets)

        if self.noise_type == 'sym':
            self.symmetric_noise()
        elif self.noise_type == 'asym':
            self.asymmetric_noise()
        elif self.noise_type == 'ins':
            self.instance_noise(tau=self.percent)

    def symmetric_noise(self):
        type = 1 #1 works better, can contain the correct label

        if type == 1:
            indices = np.random.permutation(len(self.data))
            for i, idx in enumerate(indices):
                if i < self.percent * len(self.data):
                    self.targets[idx] = np.random.randint(
                        low=self.min_target,
                        high=self.max_target + 1,
                        dtype=np.int32)
        else:
            random_state = 0
            if self.num_classes == 10:
                dataset = 'cifar10'
            elif self.num_classes == 100:
                dataset = 'cifar100'
            train_noisy_labels, actual_noise_rate = noisify(
                dataset=dataset,
                train_labels=np.array(self.targets).reshape([50000, 1]),
                noise_type=self.noise_type,
                noise_rate=self.percent,
                random_state=random_state,
                nb_classes=self.num_classes)
            self.targets = [int(label) for label in train_noisy_labels]
            print("Actual noise rate is %.4f" % actual_noise_rate)

    def asymmetric_noise(self):
        type = 1 #2 antes
        if type == 1:
            target_copy = self.targets.copy()
            if self.asym_trans == None:
                indices = np.arange(self.num_samples)
                np.random.shuffle(indices)
                idx = indices[:int(self.percent * self.num_samples)]
                target_copy = np.array(target_copy)
                target_copy[idx] = (target_copy[idx] + 1) % (
                    self.max_target + 1) + self.min_target
                self.targets = target_copy
            else:
                for i in self.asym_trans.keys():
                    indices = list(np.where(np.array(target_copy) == i)[0])
                    np.random.shuffle(indices)
                    for j, idx in enumerate(indices):
                        if j <= self.percent * len(indices):
                            self.targets[idx] = (self.asym_trans[i] if i
                                                 in self.asym_trans.keys() else
                                                 i)
            del target_copy
        else:
            random_state = 0
            # import ipdb; ipdb.set_trace()
            if self.num_classes == 10:
                dataset = 'cifar10'
            elif self.num_classes == 100:
                dataset = 'cifar100'
                self.noise_type = 'pairflip'
            train_noisy_labels, actual_noise_rate = noisify(
                dataset=dataset,
                train_labels=np.array(self.targets).reshape([50000, 1]),
                noise_type=self.noise_type,
                noise_rate=self.percent,
                random_state=random_state,
                nb_classes=self.num_classes)
            self.targets = [int(label) for label in train_noisy_labels]
            print("Actual noise rate is %.4f" % actual_noise_rate)

    def instance_noise(
        self,
        tau: float = 0.2,
        std: float = 0.1,
        feature_size: int = 3 * 32 * 32,
        # seed: int = 1
    ):
        '''
        Thanks the code from https://github.com/SML-Group/Label-Noise-Learning wrote by SML-Group.
        LabNoise referred much about the generation of instance-dependent label noise from this repo.
        '''
        from scipy import stats
        from math import inf
        import torch.nn.functional as F

        # np.random.seed(int(seed))
        # torch.manual_seed(int(seed))
        # torch.cuda.manual_seed(int(seed))

        # common-used parameters
        num_samples = self.num_samples
        num_classes = self.num_classes

        P = []
        # sample instance flip rates q from the truncated normal distribution N(\tau, {0.1}^2, [0, 1])
        flip_distribution = stats.truncnorm((0 - tau) / std, (1 - tau) / std,
                                            loc=tau,
                                            scale=std)
        '''
        The standard form of this distribution is a standard normal truncated to the range [a, b]
        notice that a and b are defined over the domain of the standard normal. 
        To convert clip values for a specific mean and standard deviation, use:

        a, b = (myclip_a - my_mean) / my_std, (myclip_b - my_mean) / my_std
        truncnorm takes  and  as shape parameters.

        so the above `flip_distribution' give a truncated standard normal distribution with mean = `tau`,
        range = [0, 1], std = `std`
        '''
        # import ipdb; ipdb.set_trace()
        # how many random variates you need to get
        q = flip_distribution.rvs(num_samples)
        # sample W \in \mathcal{R}^{S \times K} from the standard normal distribution N(0, 1^2)
        W = torch.tensor(
            np.random.randn(num_classes, feature_size,
                            num_classes)).float().to(
                                device)  #K*dim*K, dim=3072
        for i in range(num_samples):
            x, y = self.transform(Image.fromarray(self.data[i])), torch.tensor(
                self.targets[i])
            x = x.to(device)
            # step (4). generate instance-dependent flip rates
            # 1 x feature_size  *  feature_size x 10 = 1 x 10, p is a 1 x 10 vector
            p = x.reshape(1, -1).mm(W[y]).squeeze(0)  #classes
            # step (5). control the diagonal entry of the instance-dependent transition matrix
            # As exp^{-inf} = 0, p_{y} will be 0 after softmax function.
            p[y] = -inf
            # step (6). make the sum of the off-diagonal entries of the y_i-th row to be q_i
            p = q[i] * F.softmax(p, dim=0)
            p[y] += 1 - q[i]
            P.append(p)
        P = torch.stack(P, 0).cpu().numpy()
        l = [i for i in range(self.min_target, self.max_target + 1)]
        new_label = [np.random.choice(l, p=P[i]) for i in range(num_samples)]

        print('noise rate = ', (new_label != np.array(self.targets)).mean())
        self.targets = new_label




class NoiseCIFAR10(CIFAR10, NoiseDataset):

    def __init__(
        self,
        root: str,
        train: bool = True,
        transform=None,
        target_transform=None,
        download=True,
        mode: str = None,
        noise_type: str = 'none',
        percent: float = 0.0,
    ) -> None:

        self.transform_train_weak = transforms.Compose([
            transforms.RandomResizedCrop(32),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465),
                                 (0.2023, 0.1994, 0.2010)),
        ])
        self.transform_train_strong = transforms.Compose([
            transforms.RandomResizedCrop(32),
            transforms.RandomHorizontalFlip(),
            transforms.RandomApply(
                [transforms.ColorJitter(0.4, 0.4, 0.4, 0.1)], p=0.8),
            # transforms.RandomApply([GaussianBlur([.1, 2.])], p=0.5),
            transforms.RandomGrayscale(p=0.2),
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465),
                                 (0.2023, 0.1994, 0.2010)),
        ])

        self.transform_simclr = TransformsSimCLR(32) #Try 256?
        if mode == 'train_index' or mode == 'train_noisy_test' or mode =='full_train_noisy_test' or mode =='full_train_noisy_test_Fix':
            # self.transform_train = Transform2Weak_CIFAR10((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
            self.transform_train = TransformFixMatch_CIFAR10(
                (0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
        elif mode == 'train_index_2strong':
            self.transform_train = TransformFixMatch_CIFAR10(
                (0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
        elif mode == 'training_true_test':
            self.transform_train=transforms.Compose([
                transforms.ToTensor(),
                transforms.Normalize((0.4914, 0.4822, 0.4465),
                                     (0.2023, 0.1994, 0.2010)),])
        self.transform_Fix=TransformFixMatch_CIFAR10((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761))
        self.transform_test = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465),
                                 (0.2023, 0.1994, 0.2010)),
        ])

        self.root = root
        self.mode = mode
        self.transform = self.transform_test
        self.target_transform = None
        asym_trans = {
            9: 1,  # truck ->  automobile
            2: 0,  # bird  ->  airplane
            3: 5,  # cat   ->  dog
            5: 3,  # dog   ->  cat
            4: 7,  # deer  ->  horse
        }

        CIFAR10.__init__(self,
                         root=root,
                         train=train,
                         transform=transform,
                         download=download)
        NoiseDataset.__init__(self,
                              noise_type=noise_type,
                              asym_trans=asym_trans,
                              percent=percent)

    def __getitem__(self, index):
        image, target = self.data[index], self.targets[index]
        image = Image.fromarray(image)
        target2 = self.target_copy[index]

   
        if self.mode == 'train':
            img =  self.transform_simclr(image)
            return img

        elif self.mode == 'test':
            img = self.transform_test(image)
            return img, target
        



class cifar_dataloader():

    def __init__(self, cifar_type, root, batch_size, num_workers, noise_type,
                 percent):
        self.cifar_type = cifar_type
        self.root = root
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.noise_type = noise_type
        self.percent = percent

    
    def run(self, mode):  
        train_dataset = NoiseCIFAR10(root=self.root,  mode=mode)
        train_loader = DataLoader(dataset=train_dataset,
                            batch_size=self.batch_size,
                            shuffle=True,drop_last=True,
                            num_workers=self.num_workers,
                            pin_memory=True)
        test_dataset = NoiseCIFAR10(root=self.root, mode='test')
        test_loader = DataLoader(dataset=test_dataset,
                            batch_size=self.batch_size,
                            shuffle=False,
                            num_workers=self.num_workers,
                            pin_memory=True)
            

        return train_loader, test_loader




"""### Load dataset into train loader"""
torch.manual_seed(args.seed)
np.random.seed(args.seed)

if args.dataset == "STL10":
    train_dataset = torchvision.datasets.STL10(
        args.dataset_dir,
        split="unlabeled",
        download=True,
        transform=TransformsSimCLR(size=args.image_size),
    )

elif  args.dataset == "tiny_imagenet":

    tiny_imagenet_dataloaders = tiny_imagenet_dataloader(
            root_dir='tiny-imagenet-200',
            batch_size=args.batch_size,
            num_workers=args.workers,
            noise_type="sym",
            percent=0.8)
    train_mode = 'train'
    train_loader = tiny_imagenet_dataloaders.run(
            mode=train_mode)
elif args.dataset == "food101N":
    dataloaders = food101N_dataloader(
            root_dir='food-101',
            batch_size=args.batch_size,
            num_workers=1)
    train_mode = 'train'
    train_loader, testloader = dataloaders.run(mode=train_mode)
elif args.dataset == "CIFAR10":
    dataloaders = cifar_dataloader(cifar_type="cifar-10", root="CIFAR10_PAPER",
                                       batch_size=args.batch_size,
                                       num_workers=args.workers, 
                                       noise_type="sym",
                                       percent=0)

    train_loader, testloader = dataloaders.run(mode='train')
elif args.dataset == "ANIMAL10N":
    dataloaders = animal10N_dataloader(
            root_dir='Animal10Raw/',
            batch_size=args.batch_size,
            num_workers=1)
    train_mode = 'train'
    train_loader, testloader = dataloaders.run(mode=train_mode)

# elif args.dataset == "ANIMAL10":
#     train_dataset = animal10N_dataset(root_dir='Animal10Raw/', mode='train')
else:
    raise NotImplementedError

if args.nodes > 1:
    train_sampler = torch.utils.data.distributed.DistributedSampler(
        train_dataset, num_replicas=args.world_size, rank=rank, shuffle=True
    )
else:
    train_sampler = None
if args.dataset != "ANIMAL10N" and args.dataset != "tiny_imagenet"  and args.dataset != "food101N" and  args.dataset != "CIFAR10":
    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=True,
        num_workers=args.workers,
        sampler=train_sampler,
    )
"""### Load the SimCLR model, optimizer and learning rate scheduler"""

# initialize ResNet
encoder = get_resnet(args.resnet, pretrained=False)
n_features = encoder.fc.in_features  # get dimensions of fc layer

# initialize model
model = SimCLR(encoder, args.projection_dim, n_features)
if args.reload:
    model_fp = os.path.join(
        args.model_path, "checkpoint_{}.tar".format(args.epoch_num)
    )
    model.load_state_dict(torch.load(model_fp, map_location=args.device.type))
model = model.to(args.device)

# optimizer / loss
optimizer, scheduler = load_optimizer(args, model)

"""### Initialize the criterion (NT-Xent loss)"""

criterion = NT_Xent(args.batch_size, args.temperature, world_size=1)

"""### Setup TensorBoard for logging experiments"""

writer = SummaryWriter()

"""### Train function"""

def train(args, train_loader, model, criterion, optimizer, writer):
    loss_epoch = 0

    # for step, ((x_i, x_j), _) in enumerate(train_loader):
    for step,(x_i, x_j) in enumerate(train_loader):

#         (images, targets, indexes)

        optimizer.zero_grad()
        x_i = x_i.cuda(non_blocking=True)
        x_j = x_j.cuda(non_blocking=True)

        # positive pair, with encoding
        h_i, h_j, z_i, z_j = model(x_i, x_j)

        loss = criterion(z_i, z_j)
        loss.backward()

        optimizer.step()

        if step % 50 == 0:
            print(f"Step [{step}/{len(train_loader)}]\t Loss: {loss.item()}")

        writer.add_scalar("Loss/train_epoch", loss.item(), args.global_step)
        loss_epoch += loss.item()
        args.global_step += 1
    return loss_epoch

"""### Start training"""

args.global_step = 0
args.current_epoch = 0
print(args.batch_size)
print("starting trainign")
for epoch in range(args.start_epoch, args.epochs):
    lr = optimizer.param_groups[0]["lr"]
    loss_epoch = train(args, train_loader, model, criterion, optimizer, writer)

    if scheduler:
        scheduler.step()

    # save every 10 epochs
    if epoch % 50 == 0:
        save_model(args, model, optimizer)

    writer.add_scalar("Loss/train", loss_epoch / len(train_loader), epoch)
    writer.add_scalar("Misc/learning_rate", lr, epoch)
    print(
        f"Epoch [{epoch}/{args.epochs}]\t Loss: {loss_epoch / len(train_loader)}\t lr: {round(lr, 5)}"
    )
    args.current_epoch += 1

# end training
save_model(args, model, optimizer)
